services:
  node:
    build:
      context: ./backend
    container_name: node-container
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    build:
      context: ./backend/db
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "8080:80"

volumes:
  postgres_data:
