services:
  node:
    build:
      context: ./backend
    container_name: node-container
    ports:
      - "8081:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - POSTGRES_HOST=10.6.131.191  # Direcci칩n IP del contenedor postgres (m치quina 2)
    networks:
      - backend_network

  postgres:
    build:
      context: ./backend/db
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "8080:80"
    environment:
      - API_URL=http://10.6.129.133:8081  # Direcci칩n del contenedor backend (m치quina 1)
    networks:
      - frontend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
